### ISSUE TITLE
Should also update focus

### ISSUE THREAD

**Issue by danielnixon** [bluframe/react-router-scroll-top#10]
Should also do something like `document.documentElement.focus()` or `document.body.focus()` at the same time as scrolling to the top of the page.

See e.g. https://simplyaccessible.com/article/spangular-accessibility/#acc-heading-3

**Comment by edoardo-bluframe** [comment]
Hey @danielnixon Cheers for the accessibility heads up!

Wanna make a PR?? :smile:
